npm publish ./packages/afr
npm publish ./packages/amh
npm publish ./packages/ara
npm publish ./packages/asm
npm publish ./packages/aze
npm publish ./packages/aze_cyrl
npm publish ./packages/bel
npm publish ./packages/ben
npm publish ./packages/bod
npm publish ./packages/bos
npm publish ./packages/bre
npm publish ./packages/bul
npm publish ./packages/cat
npm publish ./packages/ceb
npm publish ./packages/ces
npm publish ./packages/chi_sim
npm publish ./packages/chi_sim_vert
npm publish ./packages/chi_tra
npm publish ./packages/chi_tra_vert
npm publish ./packages/chr
npm publish ./packages/cos
npm publish ./packages/cym
npm publish ./packages/dan
npm publish ./packages/dan_frak
npm publish ./packages/deu
npm publish ./packages/deu_frak
npm publish ./packages/div
npm publish ./packages/dzo
npm publish ./packages/ell
npm publish ./packages/eng
npm publish ./packages/enm
npm publish ./packages/epo
npm publish ./packages/equ
npm publish ./packages/est
npm publish ./packages/eus
npm publish ./packages/fao
npm publish ./packages/fas
npm publish ./packages/fil
npm publish ./packages/fin
npm publish ./packages/fra
npm publish ./packages/frk
npm publish ./packages/frm
npm publish ./packages/fry
npm publish ./packages/gla
npm publish ./packages/gle
npm publish ./packages/glg
npm publish ./packages/grc
npm publish ./packages/guj
npm publish ./packages/hat
npm publish ./packages/heb
npm publish ./packages/hin
npm publish ./packages/hrv
npm publish ./packages/hun
npm publish ./packages/hye
npm publish ./packages/iku
npm publish ./packages/ind
npm publish ./packages/isl
npm publish ./packages/ita
npm publish ./packages/ita_old
npm publish ./packages/jav
npm publish ./packages/jpn
npm publish ./packages/jpn_vert
npm publish ./packages/kan
npm publish ./packages/kat
npm publish ./packages/kat_old
npm publish ./packages/kaz
npm publish ./packages/khm
npm publish ./packages/kir
npm publish ./packages/kmr
npm publish ./packages/kor
npm publish ./packages/kor_vert
npm publish ./packages/kur
npm publish ./packages/kur_ara
npm publish ./packages/lao
npm publish ./packages/lat
npm publish ./packages/lav
npm publish ./packages/lit
npm publish ./packages/ltz
npm publish ./packages/mal
npm publish ./packages/mar
npm publish ./packages/mkd
npm publish ./packages/mlt
npm publish ./packages/mon
npm publish ./packages/mri
npm publish ./packages/msa
npm publish ./packages/mya
npm publish ./packages/nep
npm publish ./packages/nld
npm publish ./packages/nor
npm publish ./packages/occ
npm publish ./packages/oci
npm publish ./packages/ori
npm publish ./packages/osd
npm publish ./packages/pan
npm publish ./packages/pol
npm publish ./packages/por
npm publish ./packages/pus
npm publish ./packages/que
npm publish ./packages/ron
npm publish ./packages/rus
npm publish ./packages/san
npm publish ./packages/sin
npm publish ./packages/slk
npm publish ./packages/slk_frak
npm publish ./packages/slv
npm publish ./packages/snd
npm publish ./packages/spa
npm publish ./packages/spa_old
npm publish ./packages/sqi
npm publish ./packages/srp
npm publish ./packages/srp_latn
npm publish ./packages/sun
npm publish ./packages/swa
npm publish ./packages/swe
npm publish ./packages/syr
npm publish ./packages/tam
npm publish ./packages/tat
npm publish ./packages/tel
npm publish ./packages/tgk
npm publish ./packages/tgl
npm publish ./packages/tha
npm publish ./packages/tir
npm publish ./packages/ton
npm publish ./packages/tur
npm publish ./packages/uig
npm publish ./packages/ukr
npm publish ./packages/urd
npm publish ./packages/uzb
npm publish ./packages/uzb_cyrl
npm publish ./packages/vie
npm publish ./packages/yid
npm publish ./packages/yor
